name: Example Applications

on:
  pull_request:
    branches: [main]

# Cancel in-progress workflows from the same pull-request branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_example:
    name: "Build Example Applications"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build FreeRTOS Example
        working-directory: example/freertos
        run: |
          cmake -B build -S . -G Ninja
          cmake --build build
      - name: Build Baremetal Example
        working-directory: example/baremetal
        run: |
          cmake -B build -S . -G Ninja
          cmake --build build
