name: Pull Request Acceptance
on:
  pull_request:
    branches: [main]

# Cancel in-progress workflows from the same pull-request branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build And Test
        working-directory: extra
        run: |
          for implementation in baremetal freertos posix; do
            cmake -B build -S . -G Ninja -DIMPLEMENTATION=$implementation
            cmake --build build
            cmake --build build --target test
          done
