name: Pull Request Acceptance
on:
  pull_request:
    branches: [main]

# Cancel in-progress workflows from the same pull-request branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build Tests And Examples
        working-directory: extra
        run: |
          cmake -B build -S . -G Ninja
          cmake --build build
      - name: Baremetal Tests
        working-directory: extra
        run: ./build/test/baremetal_eventrouter_test
      - name: FreeRTOS Tests
        working-directory: extra
        run: ./build/test/freertos_eventrouter_test
